# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myFirstApp.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(829, 491)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 50, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.nameTxt = QtWidgets.QLineEdit(self.centralwidget)
        self.nameTxt.setGeometry(QtCore.QRect(350, 50, 291, 31))
        self.nameTxt.setObjectName("nameTxt")
        self.checkNameBtn = QtWidgets.QPushButton(self.centralwidget)
        self.checkNameBtn.setGeometry(QtCore.QRect(350, 130, 141, 31))
        self.checkNameBtn.setObjectName("checkNameBtn")
        self.mainoutput = QtWidgets.QLabel(self.centralwidget)
        self.mainoutput.setGeometry(QtCore.QRect(110, 190, 601, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mainoutput.setFont(font)
        self.mainoutput.setText("")
        self.mainoutput.setObjectName("mainoutput")
        self.stpw = QtWidgets.QLabel(self.centralwidget)
        self.stpw.setGeometry(QtCore.QRect(110, 370, 521, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stpw.setFont(font)
        self.stpw.setText("")
        self.stpw.setObjectName("stpw")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Password Genarator"))
        self.label.setText(_translate("MainWindow", "Enter Password"))
        self.checkNameBtn.setText(_translate("MainWindow", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
